# Seminar 2

In [2]:
import numpy as np
import seaborn as sns
import pandas as pd

penguins = sns.load_dataset("penguins")

## Descriere/Explorare dataset

In [6]:
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

In [8]:
penguins.info()

<class 'pandas.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    str
 1   island             344 non-null    str
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    str
dtypes: float64(4), str(3)
memory usage: 18.9 KB

In [9]:
penguins.select_dtypes(include="number").mean()

bill_length_mm         43.921930
bill_depth_mm          17.151170
flipper_length_mm     200.915205
body_mass_g          4201.754386
dtype: float64

In [10]:
penguins.describe()

       bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
count      342.000000     342.000000         342.000000   342.000000
mean        43.921930      17.151170         200.915205  4201.754386
std          5.459584       1.974793          14.061714   801.954536
min         32.100000      13.100000         172.000000  2700.000000
25%         39.225000      15.600000         190.000000  3550.000000
50%         44.450000      17.300000         197.000000  4050.000000
75%         48.500000      18.700000         213.000000  4750.000000
max         59.600000      21.500000         231.000000  6300.000000

In [11]:
penguins.isnull()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,True,True,True,True,True
4,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...
339,False,False,True,True,True,True,True
340,False,False,False,False,False,False,False
341,False,False,False,False,False,False,False
342,False,False,False,False,False,False,False
343,False,False,False,False,False,False,False

In [12]:
penguins.isna()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,True,True,True,True,True
4,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...
339,False,False,True,True,True,True,True
340,False,False,False,False,False,False,False
341,False,False,False,False,False,False,False
342,False,False,False,False,False,False,False
343,False,False,False,False,False,False,False

In [15]:
pd.DataFrame(penguins.isna().sum())

                    0
species             0
island              0
bill_length_mm      2
bill_depth_mm       2
flipper_length_mm   2
body_mass_g         2
sex                11

//pd.DataFrame(...) organizeaza datele sub forma de tabel(daca ai pro se face organizeaza automat saub forma de tabel)

In [18]:
penguins[penguins.columns[2:]].groupby("sex").aggregate("mean")

        bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
sex
Female       42.096970      16.425455         197.363636  3862.272727
Male         45.854762      17.891071         204.505952  4545.684524

// facem toti pinguinii cu greutate sub 4 kg sa fie femele

#### versiunea 1

In [27]:
penguins.loc[penguins['body_mass_g'] < 4000, 'sex'] = 'Female'
penguins.loc[penguins['body_mass_g'] >= 4000, 'sex'] = 'Male'
penguins.isna().sum()

species              0
island               0
bill_length_mm       2
bill_depth_mm        2
flipper_length_mm    2
body_mass_g          2
sex                  2
dtype: int64

// apare ca doi pinguini nu au sex pentru ca nu au greutate, deci nu au cum sa compare cu 4000

In [28]:
penguins[penguins['sex'].isna()]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN

#### versiunea 2

In [31]:
penguins = sns.load_dataset("penguins")
penguins["sex"] = np.where(
    penguins["sex"].isna(),
    np.where(penguins["body_mass_g"]<4000,
            "Female",
            np.where(penguins["body_mass_g"]>= 4000,
                     "Male",
                     None)),
    penguins["sex"])

penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

// a doua e mai precisa, la prima imi punea la un pinguin male doar pentru ca nu avea greutatea mai mica de 4000, chiar daca pinguinul ala nu avea greutate

In [32]:
penguins = penguins.dropna()

penguins.isna().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [33]:
penguins["bill_area"] = penguins["bill_length_mm"] * penguins["bill_depth_mm"]
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,bill_area
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,731.17
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,687.30
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,725.40
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,708.31
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male,809.58

In [34]:
penguins[["species","bill_length_mm","bill_depth_mm", "flipper_length_mm","bill_area"]].groupby("species").aggregate("mean")

           bill_length_mm  bill_depth_mm  flipper_length_mm   bill_area
species
Adelie          38.791391      18.346358         189.953642  712.940927
Chinstrap       48.833824      18.420588         195.823529  901.989118
Gentoo          47.504878      14.982114         217.186992  713.653252